#!/bin/bash
# Setup script for test-multi-cli
# Generated by Goobits CLI Framework

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project information
PACKAGE_NAME="test-multi-cli"
COMMAND_NAME="testmulti"
DISPLAY_NAME="test-multi-cli"

echo -e "${BLUE}Setting up ${DISPLAY_NAME}...${NC}"

# Check if Rust is installed
if ! command -v rustc &> /dev/null; then
    echo -e "${RED}Error: Rust is not installed${NC}"
    echo "Please install Rust from https://rustup.rs/"
    exit 1
fi

# Check if Cargo is installed
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}Error: Cargo is not installed${NC}"
    echo "Please install Cargo (usually comes with Rust)"
    exit 1
fi

echo -e "${GREEN}✓ Rust and Cargo are installed${NC}"

# Check if Cargo.toml exists
if [ ! -f Cargo.toml ]; then
    echo -e "${YELLOW}⚠ Cargo.toml not found, creating minimal configuration...${NC}"
    cat > Cargo.toml << 'EOF'
[package]
name = "test-multi-cli"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "testmulti"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive", "color"] }
clap_complete = "4.4"
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
log = "0.4"
env_logger = "0.10"
colored = "2.0"
EOF
    echo -e "${GREEN}✓ Created Cargo.toml with essential dependencies${NC}"
fi

# Check if src/hooks.rs exists
if [ ! -f src/hooks.rs ]; then
    echo -e "${YELLOW}⚠ src/hooks.rs not found, creating stub...${NC}"
    mkdir -p src
    cat > src/hooks.rs << 'EOF'
use clap::ArgMatches;
use anyhow::Result;

// Add your command implementations here
pub fn on_default(_matches: &ArgMatches) -> Result<()> {
    println!("Command not yet implemented");
    Ok(())
}
EOF
    echo -e "${GREEN}✓ Created src/hooks.rs stub${NC}"
fi

# Build the project
echo -e "${BLUE}Building ${PACKAGE_NAME}...${NC}"
if cargo build --release; then
    echo -e "${GREEN}✓ Build completed successfully${NC}"
else
    echo -e "${RED}✗ Build failed${NC}"
    exit 1
fi

# Install the binary
echo -e "${BLUE}Installing ${COMMAND_NAME}...${NC}"
if cargo install --path .; then
    echo -e "${GREEN}✓ Installation completed successfully${NC}"
else
    echo -e "${RED}✗ Installation failed${NC}"
    exit 1
fi

# Verify installation
if command -v "$COMMAND_NAME" &> /dev/null; then
    echo -e "${GREEN}✓ ${COMMAND_NAME} is now available in your PATH${NC}"
    echo -e "${BLUE}Version: $($COMMAND_NAME --version)${NC}"
else
    echo -e "${YELLOW}⚠ ${COMMAND_NAME} was installed but is not in your PATH${NC}"
    echo "You may need to add ~/.cargo/bin to your PATH"
fi

echo -e "${GREEN}Setup complete! You can now use '${COMMAND_NAME}' command.${NC}"
echo -e "${BLUE}Run '${COMMAND_NAME} --help' to get started.${NC}"