#!/usr/bin/env python3
"""
Test Python CLI - Test CLI for Python validation
Generated by Goobits CLI Framework
"""

import click
import sys
from typing import Any
try:
    from .hooks import *  # Import all hook functions
except ImportError:
    # Hooks not implemented yet
    pass
@click.group(
    name="testcli",
    help="None",
    context_settings={"help_option_names": ["-h", "--help"]}
)
@click.version_option(version="1.0.0")
def cli():
    """None"""
    pass
@cli.command(name="greet", help="Greet someone")
@click.option(
    "----loud",
    help="Greet loudly",)
def greet_command(__loud):
    """Greet someone"""
    try:
        # Call the hook function if it exists
        hook_name = "on_greet"
        if hook_name in globals():
            hook_func = globals()[hook_name]
            hook_func(__loud)
        else:
            click.echo(f"Hook function '{hook_name}' not implemented")
            sys.exit(1)
    except Exception as e:
        click.echo(f"Error: {e}", err=True)
        sys.exit(1)
if __name__ == "__main__":
    cli()