#!/usr/bin/env python3
"""
Debug script to check what gets generated in CLI files.
"""

import os
import sys
import tempfile
import subprocess
import yaml

# Add the source directory to path
sys.path.insert(0, '/workspace/src')

def debug_python_generation():
    """Debug Python CLI generation to see what's included."""
    print("=== Debugging Python CLI Generation ===")
    
    with tempfile.TemporaryDirectory() as temp_dir:
        config = {
            'package_name': 'debug-python-logger',
            'command_name': 'debugpython',
            'display_name': 'Debug Python Logger',
            'description': 'Debug Python CLI generation',
            'language': 'python',
            'cli_output_path': f'{temp_dir}/cli.py',
            
            'python': {
                'minimum_version': '3.8',
                'maximum_version': '3.13'
            },
            
            'installation': {
                'pypi_name': 'debug-python-logger'
            },
            
            'shell_integration': {
                'enabled': False,
                'alias': 'debugpython'
            },
            
            'validation': {
                'check_api_keys': False,
                'check_disk_space': False
            },
            
            'cli': {
                'name': 'debugpython',
                'tagline': 'Debug Python CLI',
                'description': 'Debug Python CLI generation',
                'commands': {
                    'hello': {
                        'desc': 'Say hello',
                        'args': [
                            {
                                'name': 'name',
                                'desc': 'Name to greet',
                                'type': 'string',
                                'required': True
                            }
                        ]
                    }
                }
            }
        }
        
        config_file = os.path.join(temp_dir, 'goobits.yaml')
        with open(config_file, 'w') as f:
            yaml.dump(config, f)
        
        # Generate CLI
        build_cmd = [sys.executable, '-m', 'goobits_cli.main', 'build', config_file]
        result = subprocess.run(build_cmd, cwd=temp_dir, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"Build failed: {result.stderr}")
            return
        
        # Read and analyze generated file
        cli_file = config['cli_output_path']
        if os.path.exists(cli_file):
            with open(cli_file, 'r') as f:
                content = f.read()
            
            print(f"Generated file size: {len(content)} characters")
            print("\nFile content preview (first 1000 chars):")
            print("=" * 50)
            print(content[:1000])
            print("=" * 50)
            
            # Check for any logging-related imports or functions
            logging_terms = [
                'import logging', 'from logging', 'setup_logging', 'get_logger',
                'contextvars', 'ContextVar', 'structured', 'logger', 'log_'
            ]
            
            found_terms = []
            for term in logging_terms:
                if term in content:
                    found_terms.append(term)
            
            if found_terms:
                print(f"\nFound logging-related terms: {found_terms}")
            else:
                print("\nNo logging-related terms found")
            
            # Check what templates were used
            if "# Generated by Goobits CLI Framework" in content:
                print("\nUsing standard templates")
            else:
                print("\nTemplate source unclear")
                
        else:
            print("CLI file was not generated")

def debug_universal_templates():
    """Debug universal template usage."""
    print("\n=== Debugging Universal Template Usage ===")
    
    with tempfile.TemporaryDirectory() as temp_dir:
        config = {
            'package_name': 'debug-universal-logger',
            'command_name': 'debuguniversal',
            'display_name': 'Debug Universal Logger',
            'description': 'Debug universal template generation',
            'language': 'python',
            'cli_output_path': f'{temp_dir}/cli.py',
            
            'python': {
                'minimum_version': '3.8',
                'maximum_version': '3.13'
            },
            
            'installation': {
                'pypi_name': 'debug-universal-logger'
            },
            
            'shell_integration': {
                'enabled': False,
                'alias': 'debuguniversal'
            },
            
            'validation': {
                'check_api_keys': False,
                'check_disk_space': False
            },
            
            'cli': {
                'name': 'debuguniversal',
                'tagline': 'Debug Universal CLI',
                'description': 'Debug universal template generation',
                'commands': {
                    'hello': {
                        'desc': 'Say hello',
                        'args': [
                            {
                                'name': 'name',
                                'desc': 'Name to greet',
                                'type': 'string',
                                'required': True
                            }
                        ]
                    }
                }
            }
        }
        
        config_file = os.path.join(temp_dir, 'goobits.yaml')
        with open(config_file, 'w') as f:
            yaml.dump(config, f)
        
        # Generate CLI with universal templates
        build_cmd = [sys.executable, '-m', 'goobits_cli.main', 'build', config_file, '--universal-templates']
        result = subprocess.run(build_cmd, cwd=temp_dir, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"Universal build failed: {result.stderr}")
            print(f"Stdout: {result.stdout}")
            return
        
        # Read and analyze generated file
        cli_file = config['cli_output_path']
        if os.path.exists(cli_file):
            with open(cli_file, 'r') as f:
                content = f.read()
            
            print(f"Universal template generated file size: {len(content)} characters")
            
            # Check for logging-related content
            logging_indicators = ['import logging', 'setup_logging', 'get_logger', 'contextvars']
            found_indicators = [ind for ind in logging_indicators if ind in content]
            
            if found_indicators:
                print(f"✓ Found logging indicators: {found_indicators}")
                
                print("\nLogging-related content preview:")
                lines = content.split('\n')
                for i, line in enumerate(lines):
                    if any(ind in line for ind in logging_indicators):
                        start = max(0, i-2)
                        end = min(len(lines), i+3)
                        print(f"Lines {start+1}-{end}:")
                        for j in range(start, end):
                            marker = ">>> " if j == i else "    "
                            print(f"{marker}{j+1}: {lines[j]}")
                        print()
                        break
            else:
                print("✗ No logging indicators found in universal template")
                
        else:
            print("Universal template CLI file was not generated")

def main():
    """Debug CLI generation to understand logging integration."""
    debug_python_generation()
    debug_universal_templates()

if __name__ == "__main__":
    main()