#!/usr/bin/env node
/**
 * Test CLI - A test CLI for universal templates
 * Generated by Goobits CLI Framework
 */

import { Command } from 'commander';
import * as hooks from './hooks';

const program = new Command();

program
    .name('test-cli')
    .description('Test CLI description')
    .version('1.0.0');
program.option(
    '--debug, -d',
    'Enable debug mode'
);

program
    .command('hello')
    .description('Say hello')
    .argument('name', 'Name to greet')
    .option('--uppercase, -u', 'Convert to uppercase')
    .action(async (name: string, options: any) => {
        try {
            const hookName = 'on_hello' as keyof typeof hooks;
            if (typeof hooks[hookName] === 'function') {
                await (hooks[hookName] as Function)(name, options);
            } else {
                console.error(`Hook function '${hookName}' not implemented`);
                process.exit(1);
            }
        } catch (error) {
            console.error('Error:', (error as Error).message);
            process.exit(1);
        }
    });

program.parse();