"""
Universal Template Engine for Goobits CLI Framework

This module provides the core engine for generating CLI implementations
across multiple programming languages using a unified template system.

The engine supports:
- Language-agnostic intermediate representation (IR)
- Multi-language rendering (Python, Node.js, TypeScript, Rust)
- Template caching and performance optimization
- Component-based architecture
- Hierarchical command structures
"""

import asyncio
import time
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Dict, Any, List, Optional

import jinja2

from .component_registry import ComponentRegistry
from .command_hierarchy import CommandFlattener, HierarchyBuilder

# Lazy import for heavy Pydantic schemas
_config_schema = None


def _get_config_schema():
    """Lazy load GoobitsConfigSchema to avoid Pydantic import overhead."""
    global _config_schema
    if _config_schema is None:
        from ..schemas import GoobitsConfigSchema

        _config_schema = GoobitsConfigSchema
    return _config_schema


# Import shared _safe_to_dict function
from ..generators import _safe_to_dict


def _safe_get_attr(obj: Any, attr: str, default: Any = "") -> Any:
    """
    Safely get an attribute from an object or dict.

    This handles cases where the object might be:
    - A Pydantic model with attributes
    - A plain dictionary with keys
    - None or other types

    Args:
        obj: Object to get attribute from
        attr: Attribute name to get
        default: Default value if attribute not found

    Returns:
        Attribute value or default
    """
    if obj is None:
        return default

    # If it's a dictionary, use dict access
    if isinstance(obj, dict):
        return obj.get(attr, default)

    # If it's an object with attributes, use getattr
    if hasattr(obj, attr):
        return getattr(obj, attr, default)

    # If it's a dict-like object that doesn't respond to hasattr properly
    try:
        return obj[attr] if attr in obj else default
    except (TypeError, KeyError):
        pass

    return default


# Import performance optimization components
try:
    from .performance.cache import TemplateCache
    from .performance.lazy_loader import LazyLoader
    from .performance.parallel_io import ParallelIOManager, write_files_batch

    PERFORMANCE_AVAILABLE = True
except ImportError:
    PERFORMANCE_AVAILABLE = False

    # Create placeholder classes for when performance features aren't available
    class TemplateCache:
        def __init__(self, *args, **kwargs):
            pass

    class LazyLoader:
        def __init__(self, *args, **kwargs):
            pass

    class ParallelIOManager:
        def __init__(self, *args, **kwargs):
            pass


class LanguageRenderer(ABC):
    """
    Abstract base class for language-specific renderers.

    Each supported language (Python, Node.js, TypeScript, Rust) must
    implement this interface to provide language-specific rendering logic.

    This class defines the contract for:
    - Language identification
    - File extension mapping
    - Template context transformation
    - Custom Jinja2 filters
    - Component rendering
    - Output file structure
    """

    @property
    @abstractmethod
    def language(self) -> str:
        """Return the language name (e.g., 'python', 'nodejs', 'typescript', 'rust')"""

        pass

    @property
    @abstractmethod
    def file_extensions(self) -> Dict[str, str]:
        """Return mapping of component types to file extensions for this language"""

        pass

    @abstractmethod
    def get_template_context(self, ir: Dict[str, Any]) -> Dict[str, Any]:
        """

        Transform the intermediate representation into language-specific template context.



        Args:

            ir: Intermediate representation generated by UniversalTemplateEngine



        Returns:

            Language-specific template context for rendering

        """

        pass

    @abstractmethod
    def get_custom_filters(self) -> Dict[str, callable]:
        """

        Return custom Jinja2 filters specific to this language.



        Returns:

            Dictionary mapping filter names to filter functions

        """

        pass

    def _set_language_context(self, ir: Dict[str, Any]) -> Dict[str, Any]:
        """
        Helper method to set language context from IR, ensuring consistent language setting.

        Args:
            ir: Intermediate representation dictionary

        Returns:
            Context dictionary with language field set to this renderer's language
        """
        context = ir.copy()
        context["language"] = self.language
        return context

    @abstractmethod
    def render_component(
        self, component_name: str, template_content: str, context: Dict[str, Any]
    ) -> str:
        """

        Render a specific component template for this language.



        Args:

            component_name: Name of the component being rendered

            template_content: The universal template content

            context: Language-specific template context



        Returns:

            Rendered template content for this language

        """

        pass

    @abstractmethod
    def get_output_structure(self, ir: Dict[str, Any]) -> Dict[str, str]:
        """

        Define the output file structure for this language.



        Args:

            ir: Intermediate representation



        Returns:

            Dictionary mapping component names to output file paths

        """

        pass


class UniversalTemplateEngine:
    """
    Main engine for the Universal Template System.

    This class orchestrates the entire process of converting a Goobits
    configuration into language-specific CLI implementations using
    universal component templates with performance optimizations.

    Key features:
    - Language-agnostic intermediate representation (IR) generation
    - Multi-language renderer support
    - Template caching and lazy loading
    - Parallel I/O for improved performance
    - Component-based template system
    - Hierarchical command structure support
    """

    def __init__(
        self,
        template_dir: Optional[Path] = None,
        template_cache: Optional[TemplateCache] = None,
        enable_lazy_loading: bool = True,
        test_mode: bool = False,
    ) -> None:
        """
        Initialize the universal template engine.

        Args:
            template_dir: Path to templates directory (alias for components_dir for backward compatibility)
            template_cache: Optional template cache for performance optimization
            enable_lazy_loading: Whether to enable lazy loading of components
            test_mode: When True, disables performance optimizations and caching for testing

        Raises:
            ValueError: If template_dir does not exist
        """

        # Validate template directory exists
        if template_dir is not None and not template_dir.exists():
            raise ValueError(f"Template directory does not exist: {template_dir}")

        # For backward compatibility, support both template_dir and components_dir

        self.template_dir = template_dir

        self.component_registry = ComponentRegistry(template_dir)

        self.renderers: Dict[str, LanguageRenderer] = {}

        # Lazy initialization for Jinja environment
        self._jinja_env = None
        self._jinja_initialized = False

        # Store test mode for cache bypass

        self.test_mode = test_mode

        # Performance optimization components

        if PERFORMANCE_AVAILABLE and not test_mode:

            if template_cache is not None:

                self.template_cache = template_cache

            else:

                # Create default template cache when performance is available

                self.template_cache = TemplateCache()

            self.performance_enabled = True

            # Initialize parallel I/O manager for concurrent file operations
            self.io_manager = ParallelIOManager(max_workers=4, use_async=True)

        else:

            self.template_cache = None

            self.performance_enabled = False

            self.io_manager = None

        # Lazy loading setup

        if enable_lazy_loading and PERFORMANCE_AVAILABLE:

            self.lazy_loader = LazyLoader()

            self._register_lazy_components()

        else:

            self.lazy_loader = None

            # Load components immediately if no lazy loading

            self.component_registry.load_components()

    def _get_jinja_env(self):
        """Lazy load Jinja2 environment to avoid import overhead."""
        if not self._jinja_initialized:
            if self.template_dir:
                self._jinja_env = jinja2.Environment(
                    loader=jinja2.FileSystemLoader(
                        str(self.template_dir), encoding="utf-8"
                    ),
                    autoescape=False,
                    trim_blocks=True,
                    lstrip_blocks=True,
                    # Enable optimized Unicode handling
                    finalize=lambda x: x if x is not None else "",
                )
            else:
                self._jinja_env = jinja2.Environment(
                    autoescape=False,
                    trim_blocks=True,
                    lstrip_blocks=True,
                    # Enable optimized Unicode handling
                    finalize=lambda x: x if x is not None else "",
                )
            self._jinja_initialized = True
        return self._jinja_env

    @property
    def jinja_env(self):
        """Get the Jinja2 environment, initializing it if necessary."""
        return self._get_jinja_env()

    def _register_lazy_components(self):
        """Register components for lazy loading"""

        if not self.lazy_loader:

            return

        # Register component loading

        self.lazy_loader.register(
            "component_registry",
            lambda: self._load_component_registry(),
            dependencies=[],
        )

        # Register renderer components

        for language in ["python", "nodejs", "typescript", "rust"]:

            self.lazy_loader.register(
                f"{language}_renderer",
                lambda lang=language: self._create_renderer(lang),
                dependencies=["component_registry"],
            )

    def _load_component_registry(self):
        """Load component registry (for lazy loading)"""

        self.component_registry.load_components()

        return self.component_registry

    def _create_renderer(self, language: str):
        """Create a renderer for the specified language (for lazy loading)"""

        # This would normally import and create the appropriate renderer

        # For now, return a placeholder

        return None

    def register_renderer(self, language: str, renderer: LanguageRenderer) -> None:
        """

        Register a language-specific renderer.



        Args:

            language: Language name (for backward compatibility with test signature)

            renderer: Language renderer implementation



        Raises:

            ValueError: If renderer is None or invalid

        """

        if renderer is None:

            raise ValueError("Renderer cannot be None")

        if not isinstance(renderer, LanguageRenderer):

            raise ValueError(
                f"Renderer must implement LanguageRenderer interface, got {type(renderer)}"
            )

        # Use the provided language or fall back to renderer's language

        lang_name = language or renderer.language

        if not lang_name:

            raise ValueError("Language name must be provided")

        self.renderers[lang_name] = renderer

        # Registered renderer (debug info only, not user-facing)

    def get_renderer(self, language: str) -> LanguageRenderer:
        """

        Get a registered language renderer.



        Args:

            language: Target programming language



        Returns:

            Language renderer implementation



        Raises:

            ValueError: If no renderer is registered for the language

        """

        if language not in self.renderers:

            available = list(self.renderers.keys())

            raise ValueError(
                f"No renderer registered for language '{language}'. "
                f"Available renderers: {available if available else 'none'}"
            )

        return self.renderers[language]

    def create_intermediate_representation(
        self, config, config_filename: str = "goobits.yaml"
    ) -> Dict[str, Any]:
        """

        Create intermediate representation from Goobits configuration.



        This is a public interface for the internal _build_intermediate_representation method.



        Args:

            config: Validated Goobits configuration

            config_filename: Name of the configuration file (for source attribution)



        Returns:

            Intermediate representation as dictionary



        Raises:

            ValueError: If config is None or invalid

        """

        if config is None:

            raise ValueError("Configuration cannot be None")

        return self._build_intermediate_representation(config, config_filename)

    def render(self, config, language: str) -> Dict[str, Any]:
        """

        Render a configuration using the specified language renderer.



        Args:

            config: Validated Goobits configuration

            language: Target programming language



        Returns:

            Dictionary containing rendered files and metadata



        Raises:

            ValueError: If language renderer is not registered

        """

        start_time = time.time()

        if language not in self.renderers:

            available = list(self.renderers.keys())

            raise ValueError(
                f"No renderer registered for language '{language}'. "
                f"Available renderers: {available if available else 'none'}"
            )

        renderer = self.renderers[language]

        # Build intermediate representation

        ir = self.create_intermediate_representation(config)

        # Get language-specific context

        context = renderer.get_template_context(ir)

        # Get output structure from renderer

        output_structure = renderer.get_output_structure(ir)

        # Actually render components using templates

        rendered_files = {}

        template_count = 0

        for component_name, output_filename in output_structure.items():

            try:

                # Check if component exists

                if self.component_registry.has_component(component_name):

                    # Get template content

                    template_content = self.component_registry.get_component(
                        component_name
                    )

                    # Render using the renderer

                    rendered_content = renderer.render_component(
                        component_name, template_content, context
                    )

                    rendered_files[output_filename] = rendered_content

                    template_count += 1

                else:

                    # Component not found - use placeholder or skip

                    rendered_files[output_filename] = (
                        f"// Component '{component_name}' not found"
                    )

            except Exception as e:

                # Handle template rendering errors gracefully

                rendered_files[output_filename] = (
                    f"// Error rendering {component_name}: {e}"
                )

        render_time = time.time() - start_time

        result = {
            "files": rendered_files,
            "metadata": {
                "language": language,
                "template_count": template_count,
                "render_time": render_time,
            },
        }

        return result

    def generate_cli(
        self,
        config,
        language: str,
        output_dir: Path,
        consolidate: bool = False,
        config_filename: str = "goobits.yaml",
    ) -> Dict[str, str]:
        """

        Generate a complete CLI implementation for the specified language.



        Args:

            config: Validated Goobits configuration

            language: Target programming language

            output_dir: Directory to write generated files

            consolidate: Whether to consolidate multiple files into single file

            config_filename: Name of the configuration file (for source attribution)



        Returns:

            Dictionary mapping output file paths to generated content



        Raises:

            ValueError: If language renderer is not registered or config is invalid

            FileNotFoundError: If component templates are missing

            RuntimeError: If generation fails

        """

        if not config:

            raise ValueError("Configuration cannot be None or empty")

        if not language:

            raise ValueError("Language cannot be None or empty")

        if language not in self.renderers:

            available = list(self.renderers.keys())

            raise ValueError(
                f"No renderer registered for language '{language}'. "
                f"Available renderers: {available if available else 'none'}"
            )

        renderer = self.renderers[language]

        import typer

        typer.echo(f"🚀 Generating {language} CLI using Universal Template System")

        # Use lazy loading if available

        if self.lazy_loader:

            # Ensure component registry is loaded

            self.lazy_loader.get_component("component_registry")

        # Build intermediate representation (with caching if available)

        config_dict = _safe_to_dict(config)
        ir_cache_key = f"ir_{hash(str(config_dict))}"

        if self.performance_enabled and self.template_cache and not self.test_mode:

            # Try to get cached IR

            cached_ir = self.template_cache._cache.get(ir_cache_key)

            if cached_ir:

                ir = cached_ir

            else:

                ir = self._build_intermediate_representation(config, config_filename)

                # Cache the IR for future use

                self.template_cache._cache.put(ir_cache_key, ir, ttl=300)  # 5 min cache

        else:

            ir = self._build_intermediate_representation(config, config_filename)

        # Get language-specific context

        context = renderer.get_template_context(ir)

        # Add consolidation mode flag to context
        context["consolidation_mode"] = consolidate

        # Get output structure

        output_structure = renderer.get_output_structure(ir)

        # Render all components with error handling and performance optimization

        generated_files = {}

        failed_components = []

        for component_name, output_path in output_structure.items():

            try:

                if self.component_registry.has_component(component_name):

                    # Use cached template if available and not in test mode

                    if (
                        self.performance_enabled
                        and self.template_cache
                        and not self.test_mode
                    ):

                        template_path = (
                            self.component_registry.components_dir
                            / f"{component_name}.j2"
                        )

                        if template_path.exists():

                            rendered_content = self.template_cache.render_template(
                                template_path, context
                            )

                            if rendered_content is not None:

                                full_output_path = output_dir / output_path

                                generated_files[str(full_output_path)] = (
                                    rendered_content
                                )

                                continue

                    # Fallback to regular rendering

                    template_content = self.component_registry.get_component(
                        component_name
                    )

                    rendered_content = renderer.render_component(
                        component_name, template_content, context
                    )

                    full_output_path = output_dir / output_path

                    generated_files[str(full_output_path)] = rendered_content

                else:

                    typer.echo(
                        f"⚠️  Component '{component_name}' not found, skipping", err=True
                    )

                    failed_components.append(component_name)

            except Exception as e:

                typer.echo(
                    f"❌ Failed to render component '{component_name}': {e}", err=True
                )

                failed_components.append(component_name)

        # Report generation results

        typer.echo(f"✅ Generated {len(generated_files)} files for {language}")

        if failed_components:

            typer.echo(
                f"⚠️  Skipped {len(failed_components)} components: {', '.join(failed_components)}",
                err=True,
            )

        # Only raise error if all components failed AND we expected at least some components

        # If all components are simply missing (not found), treat as graceful handling

        if (
            not generated_files
            and failed_components
            and len(failed_components) == len(output_structure)
        ):

            # All requested components were missing/failed - this may be intentional for testing

            typer.echo(
                f"ℹ️  No files generated - all {len(failed_components)} requested components unavailable",
                err=True,
            )

        elif not generated_files and failed_components:

            # Some components failed with errors (not just missing)

            raise RuntimeError(
                f"No files were successfully generated for {language}. "
                f"Check that component templates exist and are valid."
            )

        # Apply consolidation if requested and supported
        if consolidate and language == "python" and generated_files:
            # Check if renderer supports consolidation
            if hasattr(renderer, "consolidate_files"):
                import typer

                typer.echo("🔄 Consolidating files using Pinliner...")
                try:
                    generated_files = renderer.consolidate_files(
                        generated_files, output_dir
                    )
                    typer.echo(
                        f"✅ Consolidation completed: {len(generated_files)} files total"
                    )
                except Exception as e:
                    typer.echo(f"⚠️  Consolidation failed: {e}", err=True)
                    # Continue with original files if consolidation fails
            else:
                typer.echo(f"⚠️  Consolidation not supported for {language}", err=True)

        return generated_files

    def generate_cli_parallel(
        self,
        config,
        language: str,
        output_dir: Path,
        consolidate: bool = False,
        config_filename: str = "goobits.yaml",
    ) -> Dict[str, str]:
        """
        Generate CLI using parallel I/O for improved performance.

        This method processes templates concurrently for 30-50% performance improvement.
        """
        # Disable parallel I/O in test mode to avoid event loop conflicts
        if self.test_mode:
            return self.generate_cli(
                config, language, output_dir, consolidate, config_filename
            )

        # Use asyncio to run the parallel version
        if self.io_manager and self.performance_enabled:
            try:
                # Create async event loop if not exists
                try:
                    loop = asyncio.get_running_loop()
                except RuntimeError:
                    loop = asyncio.new_event_loop()
                    asyncio.set_event_loop(loop)
                    should_close = True
                else:
                    should_close = False

                # Run the parallel generation
                result = loop.run_until_complete(
                    self._generate_cli_parallel_async(
                        config, language, output_dir, consolidate, config_filename
                    )
                )

                if should_close:
                    loop.close()

                return result
            except Exception as e:
                # Fallback to sequential generation with debug info
                import typer

                typer.echo(
                    f"Parallel generation failed: {e}, falling back to sequential",
                    err=True,
                )
                return self.generate_cli(
                    config, language, output_dir, consolidate, config_filename
                )
        else:
            # No parallel I/O available, use sequential
            return self.generate_cli(
                config, language, output_dir, consolidate, config_filename
            )

    async def _generate_cli_parallel_async(
        self,
        config,
        language: str,
        output_dir: Path,
        consolidate: bool = False,
        config_filename: str = "goobits.yaml",
    ) -> Dict[str, str]:
        """Async implementation of parallel CLI generation."""
        if not config or not language:
            raise ValueError("Configuration and language are required")

        if language not in self.renderers:
            raise ValueError(f"No renderer registered for language '{language}'")

        renderer = self.renderers[language]

        # Build IR and context
        ir = self._build_intermediate_representation(config, config_filename)
        context = renderer.get_template_context(ir)
        context["consolidation_mode"] = consolidate

        # Get output structure
        output_structure = renderer.get_output_structure(ir)

        # Prepare batch of files to generate
        render_tasks = []
        for component_name, output_path in output_structure.items():
            if self.component_registry.has_component(component_name):
                template_content = self.component_registry.get_component(component_name)
                full_path = output_dir / output_path

                # Create render task
                task = (component_name, template_content, context, full_path)
                render_tasks.append(task)

        # Process all templates in parallel
        generated_files = {}
        if render_tasks:
            # Render templates concurrently
            rendered_contents = await self.io_manager.process_templates_parallel(
                {name: template for name, template, _, _ in render_tasks},
                lambda template, ctx: renderer.render_component(
                    render_tasks[0][0], template, ctx
                ),
                context,
            )

            # Map results to file paths
            for (name, _, _, path), content in zip(
                render_tasks, rendered_contents.values()
            ):
                generated_files[str(path)] = content

        return generated_files

    def _build_intermediate_representation(
        self, config, config_filename: str = "goobits.yaml"
    ) -> Dict[str, Any]:
        """

        Convert Goobits configuration to intermediate representation.



        This method extracts and normalizes all information from the configuration

        into a language-agnostic format that can be consumed by any renderer.



        Args:

            config: Validated Goobits configuration



        Returns:

            Intermediate representation as dictionary

        """

        # Extract CLI schema information

        # Convert config to dict for safe access
        config_dict = _safe_to_dict(config)

        cli_config = config_dict.get("cli", {})
        cli_schema = self._extract_config_schema(cli_config)

        # Analyze feature requirements for performance optimization
        feature_requirements = self.analyze_feature_requirements(
            config, config_filename
        )

        ir = {
            "project": {
                "name": _safe_get_attr(
                    config, "display_name", _safe_get_attr(config, "command_name")
                ),
                "description": _safe_get_attr(config, "description"),
                "version": (
                    (lambda v: v if v is not None else "1.0.0")(
                        _safe_get_attr(
                            _safe_get_attr(config, "cli", {}), "version", "1.0.0"
                        )
                    )
                    if _safe_get_attr(config, "cli")
                    else "1.0.0"
                ),
                "author": _safe_get_attr(config, "author"),
                "license": _safe_get_attr(config, "license"),
                "package_name": _safe_get_attr(config, "package_name"),
                "command_name": _safe_get_attr(config, "command_name"),
                "cli_path": _safe_get_attr(config, "cli_path"),
                "cli_hooks_path": _safe_get_attr(config, "cli_hooks_path"),
                "hooks_path": _safe_get_attr(config, "hooks_path"),
            },
            "cli": cli_schema,
            "installation": {
                "pypi_name": _safe_get_attr(
                    _safe_get_attr(config, "installation", {}),
                    "pypi_name",
                    _safe_get_attr(config, "package_name"),
                ),
                "development_path": _safe_get_attr(
                    _safe_get_attr(config, "installation", {}), "development_path", "."
                ),
                "extras": _safe_to_dict(
                    _safe_get_attr(
                        _safe_get_attr(config, "installation", {}), "extras", {}
                    )
                ),
            },
            "dependencies": self._extract_dependencies(config),
            "features": _safe_to_dict(_safe_get_attr(config, "features", {})),
            # Add feature requirements for conditional template generation
            "feature_requirements": feature_requirements,
            "metadata": {
                "generated_at": "{{ timestamp }}",  # Will be replaced during rendering
                "generator_version": "{{ version }}",  # Will be replaced during rendering
                "source_config": _safe_to_dict(config),
                "config_filename": config_filename,
            },
        }

        return ir

    def _extract_config_schema(self, cli_config: Any) -> Dict[str, Any]:
        """

        Extract normalized CLI schema from configuration.



        Args:

            cli_config: CLI configuration section



        Returns:

            Normalized CLI schema

        """
        # Convert cli_config to dict for safe access
        cli_dict = _safe_to_dict(cli_config)

        schema = {
            "root_command": {
                "name": cli_dict.get("name", ""),
                "description": cli_dict.get("description", cli_dict.get("tagline", "")),
                "version": (lambda v: v if v is not None else "1.0.0")(
                    cli_dict.get("version", "1.0.0")
                ),
                "arguments": [],
                "options": [],
                "subcommands": [],
            },
            "commands": {},
            "global_options": [],
            "completion": {
                "enabled": True,  # Default to enabled
                "shells": ["bash", "zsh", "fish"],
            },
            # Preserve custom help sections
            "tagline": _safe_get_attr(
                cli_config,
                "tagline",
                _safe_get_attr(cli_config, "description", "No description"),
            ),
            "description": _safe_get_attr(cli_config, "description", "No description"),
            "header_sections": _safe_get_attr(cli_config, "header_sections", []),
            "footer_note": _safe_get_attr(cli_config, "footer_note"),
            "version": _safe_get_attr(cli_config, "version", "1.0.0"),
        }

        # Extract arguments (CLI root rarely has arguments in current schema)

        if "args" in cli_dict and cli_dict["args"]:

            for arg in cli_dict["args"]:

                schema["root_command"]["arguments"].append(
                    {
                        "name": _safe_get_attr(arg, "name"),
                        "description": _safe_get_attr(arg, "desc"),
                        "type": _safe_get_attr(arg, "type", "string"),
                        "required": _safe_get_attr(arg, "required", True),
                        "multiple": _safe_get_attr(arg, "nargs") == "*",
                        "nargs": _safe_get_attr(arg, "nargs"),
                    }
                )

        # Extract options

        if "options" in cli_dict and cli_dict["options"]:

            for opt in cli_dict["options"]:

                option_data = {
                    "name": _safe_get_attr(opt, "name"),
                    "short": _safe_get_attr(opt, "short"),
                    "description": _safe_get_attr(opt, "desc"),
                    "type": _safe_get_attr(opt, "type", "str"),
                    "default": _safe_get_attr(opt, "default"),
                    "required": False,  # Global options typically not required
                    "multiple": _safe_get_attr(opt, "multiple", False),
                }

                schema["root_command"]["options"].append(option_data)

        # Extract subcommands

        if "commands" in cli_dict and cli_dict["commands"]:
            commands = cli_dict["commands"]

            if isinstance(commands, dict):
                # Old format: {"hello": {...}}
                for cmd_name, cmd in commands.items():
                    cmd_dict = _safe_to_dict(cmd)

                    command_data = {
                        "name": cmd_name,
                        "description": cmd_dict.get(
                            "description", cmd_dict.get("desc", "")
                        ),
                        "arguments": [],
                        "options": [],
                        "subcommands": [],
                        "hook_name": f"on_{cmd_name.replace('-', '_')}",
                    }

                    # Extract command arguments
                    if "args" in cmd_dict and cmd_dict["args"]:
                        for arg in cmd_dict["args"]:
                            arg_dict = _safe_to_dict(arg)
                            command_data["arguments"].append(
                                {
                                    "name": arg_dict.get("name", ""),
                                    "description": arg_dict.get(
                                        "desc", arg_dict.get("description", "")
                                    ),
                                    "type": arg_dict.get("type", "string"),
                                    "required": arg_dict.get("required", False),
                                    "default": arg_dict.get("default"),
                                }
                            )

                    # Extract command options
                    if "options" in cmd_dict and cmd_dict["options"]:
                        for opt in cmd_dict["options"]:
                            opt_dict = _safe_to_dict(opt)
                            command_data["options"].append(
                                {
                                    "name": opt_dict.get("name", ""),
                                    "description": opt_dict.get(
                                        "desc", opt_dict.get("description", "")
                                    ),
                                    "type": opt_dict.get("type", "string"),
                                    "required": opt_dict.get("required", False),
                                    "short": opt_dict.get("short"),
                                    "default": opt_dict.get("default"),
                                    "multiple": opt_dict.get("multiple", False),
                                }
                            )

                    # Handle nested subcommands
                    if "subcommands" in cmd_dict and cmd_dict["subcommands"]:
                        command_data["subcommands"] = self._extract_subcommands_dict(
                            cmd_dict["subcommands"]
                        )

                    schema["root_command"]["subcommands"].append(command_data)
                    schema["commands"][cmd_name] = command_data

            elif isinstance(commands, list):
                # New format: [{"name": "hello", ...}]
                for cmd in commands:
                    cmd_dict = _safe_to_dict(cmd)
                    cmd_name = cmd_dict.get("name", "unknown")

                    command_data = {
                        "name": cmd_name,
                        "description": cmd_dict.get(
                            "description", cmd_dict.get("desc", "")
                        ),
                        "arguments": [],
                        "options": [],
                        "subcommands": [],
                        "hook_name": f"on_{cmd_name.replace('-', '_')}",
                    }

                    # Extract command arguments

                    if "args" in cmd_dict and cmd_dict["args"]:

                        for arg in cmd_dict["args"]:

                            command_data["arguments"].append(
                                {
                                    "name": _safe_get_attr(arg, "name"),
                                    "description": _safe_get_attr(
                                        arg, "desc"
                                    ),  # Note: ArgumentSchema uses 'desc'
                                    "type": _safe_get_attr(arg, "type", "string"),
                                    "required": _safe_get_attr(arg, "required", True),
                                    "multiple": _safe_get_attr(arg, "nargs") == "*",
                                    "nargs": _safe_get_attr(arg, "nargs"),
                                }
                            )

                    # Extract command options

                    if "options" in cmd_dict and cmd_dict["options"]:

                        for opt in cmd_dict["options"]:

                            command_data["options"].append(
                                {
                                    "name": _safe_get_attr(opt, "name"),
                                    "short": _safe_get_attr(opt, "short"),
                                    "description": _safe_get_attr(
                                        opt, "desc"
                                    ),  # Note: OptionSchema uses 'desc'
                                    "type": _safe_get_attr(opt, "type", "str"),
                                    "default": _safe_get_attr(opt, "default"),
                                    "required": False,  # Options are typically not required
                                    "multiple": _safe_get_attr(opt, "multiple", False),
                                }
                            )

                    # Handle nested subcommands recursively

                    if "subcommands" in cmd_dict and cmd_dict["subcommands"]:

                        command_data["subcommands"] = self._extract_subcommands_dict(
                            cmd_dict["subcommands"]
                        )

                    schema["root_command"]["subcommands"].append(command_data)

                    schema["commands"][cmd_name] = command_data

        # NEW: Build command hierarchy for nested command support
        if schema["commands"]:
            flattener = CommandFlattener()
            hierarchy_builder = HierarchyBuilder()

            # Extract flat commands from nested structure
            flat_commands = flattener.flatten_commands(schema["commands"])

            # Build hierarchical structure for template rendering
            command_hierarchy = hierarchy_builder.build_hierarchy(flat_commands)

            # Add hierarchy to schema for template access
            schema["command_hierarchy"] = {
                "groups": [
                    self._serialize_command_group(group)
                    for group in command_hierarchy.groups
                ],
                "leaves": [
                    self._serialize_flat_command(leaf)
                    for leaf in command_hierarchy.leaves
                ],
                "max_depth": command_hierarchy.max_depth,
                "flat_commands": [
                    self._serialize_flat_command(cmd) for cmd in flat_commands
                ],
            }
        else:
            schema["command_hierarchy"] = {
                "groups": [],
                "leaves": [],
                "max_depth": 0,
                "flat_commands": [],
            }

        return schema

    def _serialize_command_group(self, group) -> Dict[str, Any]:
        """Serialize CommandGroup for template rendering."""
        return {
            "name": group.name,
            "path": group.path,
            "description": group.description,
            "arguments": group.arguments,
            "options": group.options,
            "hook_name": group.hook_name,
            "subcommands": [
                self._serialize_command_node(node) for node in group.subcommands
            ],
            "depth": group.depth,
            "parent_path": group.path[:-1] if group.path else [],
            "click_decorator": self._get_click_decorator(group.path),
        }

    def _serialize_flat_command(self, command) -> Dict[str, Any]:
        """Serialize FlatCommand for template rendering."""
        return {
            "name": command.name,
            "path": command.path,
            "description": command.description,
            "arguments": command.arguments,
            "options": command.options,
            "hook_name": command.hook_name,
            "is_group": command.is_group,
            "parent_path": command.parent_path,
            "depth": command.depth,
            "click_decorator": self._get_click_decorator(command.path),
        }

    def _serialize_command_node(self, node) -> Dict[str, Any]:
        """Serialize CommandNode for template rendering."""
        return {
            "command": self._serialize_flat_command(node.command),
            "children": [
                self._serialize_command_node(child) for child in node.children
            ],
            "is_leaf": node.is_leaf,
        }

    def _get_click_decorator(self, command_path: List[str]) -> str:
        """Generate Click decorator for command path."""
        if len(command_path) <= 1:
            return "main"
        else:
            parent_path = command_path[:-1]
            return ".".join(parent_path).replace("-", "_")

    def _extract_subcommands_dict(
        self, commands: Dict[str, Any]
    ) -> List[Dict[str, Any]]:
        """

        Extract subcommands from dictionary format (used by CLISchema).



        Args:

            commands: Dictionary of command configurations



        Returns:

            List of normalized subcommand schemas

        """

        subcommands = []

        for cmd_name, cmd in commands.items():

            command_data = {
                "name": cmd_name,
                "description": _safe_get_attr(cmd, "desc"),
                "arguments": [],
                "options": [],
                "subcommands": [],
                "hook_name": f"on_{cmd_name.replace('-', '_')}",
            }

            # Extract arguments and options similar to main commands
            # Handle both dict and object cases
            if isinstance(cmd, dict):
                # Subcommands come as dictionaries
                args = cmd.get("args", [])
                options = cmd.get("options", [])
            else:
                # Main commands come as objects
                args = getattr(cmd, "args", []) if hasattr(cmd, "args") else []
                options = getattr(cmd, "options", []) if hasattr(cmd, "options") else []

            if args:
                for arg in args:
                    # Handle both dict and object arg formats
                    if isinstance(arg, dict):
                        arg_name = arg.get("name")
                        arg_desc = arg.get("desc", "")
                        arg_type = arg.get("type", "string")
                        arg_required = arg.get("required", True)
                        arg_nargs = arg.get("nargs")
                    else:
                        arg_name = _safe_get_attr(arg, "name")
                        arg_desc = _safe_get_attr(arg, "desc")
                        arg_type = _safe_get_attr(arg, "type", "string")
                        arg_required = _safe_get_attr(arg, "required", True)
                        arg_nargs = _safe_get_attr(arg, "nargs")

                    command_data["arguments"].append(
                        {
                            "name": arg_name,
                            "description": arg_desc,
                            "type": arg_type,
                            "required": arg_required,
                            "multiple": arg_nargs == "*",
                            "nargs": arg_nargs,
                        }
                    )

            # Options handling (already extracted above for dict case)
            if not isinstance(cmd, dict) and hasattr(cmd, "options") and cmd.options:
                options = cmd.options

            if options:

                for opt in options:
                    # Handle both dict and object option formats
                    if isinstance(opt, dict):
                        opt_name = opt.get("name")
                        opt_short = opt.get("short")
                        opt_desc = opt.get("desc", "")
                        opt_type = opt.get("type", "str")
                        opt_default = opt.get("default")
                        opt_multiple = opt.get("multiple", False)
                    else:
                        opt_name = _safe_get_attr(opt, "name")
                        opt_short = _safe_get_attr(opt, "short")
                        opt_desc = _safe_get_attr(opt, "desc")
                        opt_type = _safe_get_attr(opt, "type", "str")
                        opt_default = _safe_get_attr(opt, "default")
                        opt_multiple = _safe_get_attr(opt, "multiple", False)

                    command_data["options"].append(
                        {
                            "name": opt_name,
                            "short": opt_short,
                            "description": opt_desc,
                            "type": opt_type,
                            "default": opt_default,
                            "required": False,
                            "multiple": opt_multiple,
                        }
                    )

            # Recursively handle nested subcommands
            if isinstance(cmd, dict):
                nested_subcommands = cmd.get("subcommands")
            else:
                nested_subcommands = (
                    getattr(cmd, "subcommands", None)
                    if hasattr(cmd, "subcommands")
                    else None
                )

            if nested_subcommands:

                command_data["subcommands"] = self._extract_subcommands_dict(
                    nested_subcommands
                )

            subcommands.append(command_data)

        return subcommands

    def _extract_subcommands(self, commands: List[Any]) -> List[Dict[str, Any]]:
        """

        Recursively extract subcommands.



        Args:

            commands: List of command configurations



        Returns:

            List of normalized subcommand schemas

        """

        subcommands = []

        for cmd in commands:

            command_data = {
                "name": _safe_get_attr(cmd, "name"),
                "description": _safe_get_attr(cmd, "description"),
                "arguments": [],
                "options": [],
                "subcommands": [],
                "hook_name": f"on_{_safe_get_attr(cmd, 'name', '').replace('-', '_')}",
            }

            # Extract arguments and options similar to main commands

            if hasattr(cmd, "arguments") and cmd.arguments:

                for arg in cmd.arguments:

                    command_data["arguments"].append(
                        {
                            "name": _safe_get_attr(arg, "name"),
                            "description": _safe_get_attr(arg, "description"),
                            "type": _safe_get_attr(arg, "type", "string"),
                            "required": _safe_get_attr(arg, "required", True),
                            "multiple": _safe_get_attr(arg, "multiple", False),
                        }
                    )

            # Options handling (already extracted above for dict case)
            if not isinstance(cmd, dict) and hasattr(cmd, "options") and cmd.options:
                options = cmd.options

            if options:

                for opt in options:

                    command_data["options"].append(
                        {
                            "name": _safe_get_attr(opt, "name"),
                            "short": _safe_get_attr(opt, "short"),
                            "description": _safe_get_attr(opt, "description"),
                            "type": _safe_get_attr(opt, "type", "string"),
                            "default": _safe_get_attr(opt, "default"),
                            "required": _safe_get_attr(opt, "required", False),
                            "multiple": _safe_get_attr(opt, "multiple", False),
                        }
                    )

            # Recursively handle nested subcommands

            if hasattr(cmd, "commands") and cmd.commands:

                command_data["subcommands"] = self._extract_subcommands(cmd.commands)

            subcommands.append(command_data)

        return subcommands

    def _extract_dependencies(self, config) -> Dict[str, List[str]]:
        """

        Extract and normalize dependency information.



        Args:

            config: Goobits configuration



        Returns:

            Normalized dependencies by type

        """

        dependencies = {
            "python": [],
            "system": [],
            "npm": [],
            "rust": [],
        }

        # Extract from dependencies section

        dependencies_obj = _safe_get_attr(config, "dependencies")
        if dependencies_obj:

            # Handle required dependencies

            if _safe_get_attr(dependencies_obj, "required"):

                for dep in _safe_get_attr(dependencies_obj, "required", []):

                    if hasattr(dep, "name"):  # DependencyItem object
                        dep_name = _safe_get_attr(dep, "name")
                        dep_type = _safe_get_attr(dep, "type", "python")

                        # Only add to Python dependencies if it's not a system command
                        if dep_type != "command":
                            dependencies["python"].append(dep_name)
                        else:
                            # System commands go to system dependencies
                            dependencies["system"].append(dep_name)

                    else:  # String
                        # Assume strings are Python dependencies
                        dependencies["python"].append(dep)

            # Handle optional dependencies

            if _safe_get_attr(dependencies_obj, "optional"):

                for dep in _safe_get_attr(dependencies_obj, "optional", []):

                    if hasattr(dep, "name"):  # DependencyItem object
                        dep_name = _safe_get_attr(dep, "name")
                        dep_type = _safe_get_attr(dep, "type", "python")

                        # Only add to Python dependencies if it's not a system command
                        if dep_type != "command":
                            dependencies["python"].append(dep_name)
                        else:
                            # System commands go to system dependencies
                            dependencies["system"].append(dep_name)

                    else:  # String
                        # Assume strings are Python dependencies
                        dependencies["python"].append(dep)

        # Extract from installation extras

        installation_obj = _safe_get_attr(config, "installation")
        if installation_obj:

            extras_obj = _safe_get_attr(installation_obj, "extras")

            if extras_obj:
                # Convert Pydantic model to dict if necessary
                extras = _safe_to_dict(extras_obj)

                # Python extras from installation.extras.python are meant for optional-dependencies
                # NOT for main dependencies. Skip adding them to main dependencies to avoid
                # pip install errors like "No matching distribution found for dev"
                python_extras = extras.get("python", [])
                # NOTE: These are handled separately in pyproject.toml template as optional-dependencies

                apt_extras = extras.get("apt", [])
                if apt_extras:
                    dependencies["system"].extend(apt_extras)

                npm_extras = extras.get("npm", [])
                if npm_extras:
                    dependencies["npm"].extend(npm_extras)

                cargo_extras = extras.get("cargo", [])
                if cargo_extras:
                    dependencies["rust"].extend(cargo_extras)

        # Extract Rust crates

        if hasattr(config, "rust_crates") and config.rust_crates:

            dependencies["rust"].extend(config.rust_crates.keys())

        return dependencies

    def analyze_feature_requirements(
        self, config, config_filename: str = "goobits.yaml"
    ) -> Dict[str, Any]:
        """
        Analyze YAML config to determine required features for performance optimization.

        This method examines the configuration to determine which advanced features
        are actually needed, allowing us to generate optimized CLI variants that
        exclude unused dependencies and code.

        Args:
            config: Validated Goobits configuration
            config_filename: Name of the configuration file

        Returns:
            Dictionary with feature requirements analysis:
            {
                'rich_interface': bool,      # Needs rich_click formatting
                'interactive_mode': bool,    # Has interactive commands
                'completion_system': bool,   # Has completion subcommands
                'complex_parsing': bool,     # Has complex arguments/options
                'config_management': bool,   # Has config commands
                'async_features': bool,      # Uses async operations
                'plugin_system': bool        # Has plugin support
            }
        """
        config_dict = _safe_to_dict(config)
        cli_config = config_dict.get("cli", {})

        # Feature detection heuristics
        requirements = {
            "rich_interface": self._needs_rich_formatting(cli_config, config_dict),
            "interactive_mode": self._has_interactive_commands(cli_config),
            "completion_system": self._has_completion_subcommands(cli_config),
            "complex_parsing": self._has_complex_arguments(cli_config),
            "config_management": self._has_config_features(cli_config),
            "async_features": self._has_async_features(cli_config),
            "plugin_system": self._has_plugin_features(cli_config),
            # Enhanced granular feature detection
            "table_formatting": self._needs_table_formatting(cli_config),
            "progress_features": self._needs_progress_features(cli_config),
            "color_support": self._needs_color_support(cli_config),
            "complex_types": self._has_complex_types(cli_config),
            "file_operations": self._needs_file_operations(cli_config),
            # Node.js/TypeScript specific optimizations
            "subcommand_nesting": self._has_nested_subcommands(cli_config),
            "commander_help_formatting": self._needs_commander_help_formatting(
                cli_config
            ),
        }

        # CRITICAL FIX: rich_interface should be True if ANY rich-specific features are needed
        # This ensures CLIs that need table formatting, colors, or progress use rich_click
        rich_features = ["table_formatting", "progress_features", "color_support"]

        if any(requirements.get(feature, False) for feature in rich_features):
            requirements["rich_interface"] = True

        return requirements

    def _needs_rich_formatting(
        self, cli_config: Dict[str, Any], full_config: Dict[str, Any]
    ) -> bool:
        """
        Check if CLI needs rich formatting features.

        Conservative approach: prefer rich formatting if uncertain, but detect
        simple CLIs that can use basic Click for better performance.
        """
        # Always use rich for complex CLIs or when explicitly configured
        commands = cli_config.get("commands", {})

        # Simple heuristic: CLIs with <= 2 commands and no styling can use basic click
        if len(commands) <= 2:
            # Check if any commands have complex help, tables, colors, etc.
            for cmd in commands.values():
                cmd_dict = _safe_to_dict(cmd)
                desc = cmd_dict.get("desc", cmd_dict.get("description", ""))

                # Look for rich markup patterns
                if any(
                    marker in str(desc).lower()
                    for marker in [
                        "[bold]",
                        "[italic]",
                        "[green]",
                        "[red]",
                        "[yellow]",
                        "[blue]",
                        "[dim]",
                        "[bright]",
                        "table",
                        "progress",
                        "spinner",
                    ]
                ):
                    return True

                # Check for complex options that might benefit from rich display
                options = cmd_dict.get("options", [])
                if len(options) > 5:  # Many options look better with rich
                    return True

        # Check for header sections or footer notes (rich-specific features)
        if cli_config.get("header_sections") or cli_config.get("footer_note"):
            return True

        # Check for colors configuration
        if cli_config.get("colors", True) == False:
            return False  # Explicitly disabled

        # Default to rich for complex CLIs (> 2 commands)
        return len(commands) > 2

    def _has_interactive_commands(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI has interactive mode features."""
        features = cli_config.get("features", {})
        interactive_mode = features.get("interactive_mode", {})
        return interactive_mode.get("enabled", False)

    def _has_completion_subcommands(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI needs shell completion system."""
        completion = cli_config.get("completion", {})
        return completion.get("enabled", True)  # Default enabled

    def _has_complex_arguments(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI has complex argument parsing needs."""
        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)

            # Check for complex argument patterns
            args = cmd_dict.get("args", [])
            options = cmd_dict.get("options", [])

            # Complex if many arguments/options
            if len(args) > 3 or len(options) > 4:
                return True

            # Complex if has advanced types
            for arg in args:
                arg_dict = _safe_to_dict(arg)
                if arg_dict.get("type") in ["choice", "file", "path"]:
                    return True
                if arg_dict.get("multiple", False):
                    return True

            for opt in options:
                opt_dict = _safe_to_dict(opt)
                if opt_dict.get("type") in ["choice", "file", "path"]:
                    return True
                if opt_dict.get("multiple", False):
                    return True
                if opt_dict.get("choices"):
                    return True

        return False

    def _has_config_features(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI uses configuration management."""
        commands = cli_config.get("commands", {})
        return any("config" in str(cmd_name).lower() for cmd_name in commands.keys())

    def _has_async_features(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI uses async features."""
        # For now, assume no async features unless explicitly marked
        features = cli_config.get("features", {})
        return features.get("async", {}).get("enabled", False)

    def _has_plugin_features(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI has plugin system."""
        features = cli_config.get("features", {})
        return features.get("plugins", {}).get("enabled", False)

    def _needs_table_formatting(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI needs table formatting capabilities."""
        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            desc = str(cmd_dict.get("desc", cmd_dict.get("description", ""))).lower()

            # Look for table-related keywords
            table_keywords = [
                "table",
                "list",
                "tabulate",
                "grid",
                "column",
                "row",
                "csv",
                "export",
            ]
            if any(keyword in desc for keyword in table_keywords):
                return True

            # Check options that suggest table output
            options = cmd_dict.get("options", [])
            for opt in options:
                opt_dict = _safe_to_dict(opt)
                opt_name = str(opt_dict.get("name", "")).lower()
                opt_desc = str(
                    opt_dict.get("desc", opt_dict.get("description", ""))
                ).lower()

                if any(
                    keyword in f"{opt_name} {opt_desc}" for keyword in table_keywords
                ):
                    return True

                # Format options often indicate table output
                if "format" in opt_name and opt_dict.get("choices", []):
                    choices = [str(c).lower() for c in opt_dict.get("choices", [])]
                    if any(fmt in choices for fmt in ["table", "csv", "json"]):
                        return True

        return False

    def _needs_progress_features(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI needs progress bars, spinners, or loading indicators."""
        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            desc = str(cmd_dict.get("desc", cmd_dict.get("description", ""))).lower()

            # Look for progress-related keywords
            progress_keywords = [
                "progress",
                "loading",
                "spinner",
                "wait",
                "processing",
                "download",
                "upload",
                "install",
                "build",
            ]
            if any(keyword in desc for keyword in progress_keywords):
                return True

            # Check for verbose/quiet options that suggest long-running operations
            options = cmd_dict.get("options", [])
            for opt in options:
                opt_dict = _safe_to_dict(opt)
                opt_name = str(opt_dict.get("name", "")).lower()

                if opt_name in ["verbose", "quiet", "progress", "no-progress"]:
                    return True

        return False

    def _needs_color_support(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI explicitly needs color support."""
        # Check global color configuration
        if cli_config.get("colors") == False:
            return False  # Explicitly disabled

        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            desc = str(cmd_dict.get("desc", cmd_dict.get("description", ""))).lower()

            # Look for color-related keywords
            color_keywords = ["color", "highlight", "syntax", "theme", "style"]
            if any(keyword in desc for keyword in color_keywords):
                return True

            # Check for color options
            options = cmd_dict.get("options", [])
            for opt in options:
                opt_dict = _safe_to_dict(opt)
                opt_name = str(opt_dict.get("name", "")).lower()

                if any(
                    keyword in opt_name
                    for keyword in ["color", "no-color", "theme", "style"]
                ):
                    return True

        # Default to True if not explicitly disabled
        return cli_config.get("colors", True)

    def _has_complex_types(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI has complex type definitions (useful for TypeScript)."""
        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)

            # Check arguments and options for complex types
            for items in [cmd_dict.get("args", []), cmd_dict.get("options", [])]:
                for item in items:
                    item_dict = _safe_to_dict(item)

                    # Complex types that benefit from TypeScript interfaces
                    if item_dict.get("type") in [
                        "choice",
                        "file",
                        "path",
                        "json",
                        "object",
                    ]:
                        return True
                    if item_dict.get("multiple", False):
                        return True
                    if item_dict.get("choices"):
                        return True

                    # Check for validation rules
                    if any(
                        key in item_dict
                        for key in ["min", "max", "pattern", "validate"]
                    ):
                        return True

        return False

    def _needs_file_operations(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI needs file system operations."""
        commands = cli_config.get("commands", {})

        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            desc = str(cmd_dict.get("desc", cmd_dict.get("description", ""))).lower()

            # Look for file operation keywords
            file_keywords = [
                "file",
                "path",
                "directory",
                "folder",
                "read",
                "write",
                "copy",
                "move",
                "delete",
                "create",
                "save",
                "load",
                "import",
                "export",
            ]
            if any(keyword in desc for keyword in file_keywords):
                return True

            # Check for file/path type arguments/options
            for items in [cmd_dict.get("args", []), cmd_dict.get("options", [])]:
                for item in items:
                    item_dict = _safe_to_dict(item)
                    if item_dict.get("type") in ["file", "path"]:
                        return True

        return False

    def _has_nested_subcommands(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI has nested subcommands (affects Commander.js setup complexity)."""
        commands = cli_config.get("commands", {})

        # Look for subcommands within commands
        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            if cmd_dict.get("subcommands") or cmd_dict.get("commands"):
                return True

        # Check if we have more than 3 top-level commands (suggests complexity)
        return len(commands) > 3

    def _needs_commander_help_formatting(self, cli_config: Dict[str, Any]) -> bool:
        """Check if CLI needs enhanced Commander.js help formatting."""
        commands = cli_config.get("commands", {})

        # Check for complex help patterns that need custom formatting
        for cmd in commands.values():
            cmd_dict = _safe_to_dict(cmd)
            desc = str(cmd_dict.get("desc", cmd_dict.get("description", "")))

            # Look for multi-line descriptions or complex help text
            if len(desc) > 80 or "\n" in desc:
                return True

            # Check for many options that would benefit from grouped help
            options = cmd_dict.get("options", [])
            if len(options) > 6:
                return True

            # Check for examples or usage patterns
            if any(
                keyword in desc.lower()
                for keyword in ["example", "usage", "note:", "warning:"]
            ):
                return True

        # Check for global help customization
        if cli_config.get("help_sections") or cli_config.get("examples"):
            return True

        return False
