# Fish completion script for Demo Rust CLI (demo_rust)
# Auto-generated by goobits-cli

# Main completion function
function __demo_rust_complete
    set -l cmd (commandline -opc)
    set -l current (commandline -ct)
    
    # Try dynamic completion first
    if __demo_rust_dynamic_complete $cmd $current
        return 0
    end
    
    # Fallback to static completion
    __demo_rust_static_complete $cmd $current
end

# Dynamic completion using CLI's built-in completion
function __demo_rust_dynamic_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Check if CLI supports completion
    if not command -v demo_rust >/dev/null 2>&1
        return 1
    end
    
    # Get completion suggestions from the CLI itself
    set -l suggestions (demo_rust _completion fish (commandline -cp) (commandline -C) 2>/dev/null)
    
    if test $status -eq 0; and test -n "$suggestions"
        for suggestion in $suggestions
            echo $suggestion
        end
        return 0
    end
    
    return 1
end

# Static completion as fallback
function __demo_rust_static_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Remove the command name itself
    set -e cmd[1]
    
    # If no subcommand yet, complete with main commands
    if test (count $cmd) -eq 0
        __demo_rust_complete_commands
        return 0
    end
    
    # Handle subcommand completion
    switch $cmd[1]
        case 'greet'
            __demo_rust_complete_greet_options $cmd[2..-1]
        case 'info'
            __demo_rust_complete_info_options $cmd[2..-1]
        case 'plugin'
            __demo_rust_complete_plugin $cmd[2..-1]
        case 'upgrade'
            __demo_rust_complete_upgrade $cmd[2..-1]
        case 'help'
            __demo_rust_complete_commands
    end
end

# Complete main commands
function __demo_rust_complete_commands
    echo 'greet\tGreet someone with style'
    echo 'info\tDisplay system and environment information'
    echo 'upgrade\tUpgrade Demo Rust CLI to the latest version'
    echo 'plugin\t🔌 Manage plugins for Demo Rust CLI'
    echo 'help\tShow help information'
end

# Complete greet command options
function __demo_rust_complete_greet_options
    echo '--style\tGreeting style'
    echo '-s\tGreeting style'
    echo '--count\tRepeat greeting N times'
    echo '-c\tRepeat greeting N times'
    echo '--uppercase\tConvert to uppercase'
    echo '-u\tConvert to uppercase'
    echo '--language\tLanguage code'
    echo '-l\tLanguage code'
    echo '--help\tShow help for greet command'
    echo '-h\tShow help for greet command'
end
# Complete info command options
function __demo_rust_complete_info_options
    echo '--format\tOutput format'
    echo '-f\tOutput format'
    echo '--verbose\tShow detailed information'
    echo '-v\tShow detailed information'
    echo '--sections\tComma-separated sections to show'
    echo '-s\tComma-separated sections to show'
    echo '--help\tShow help for info command'
    echo '-h\tShow help for info command'
end

# Complete plugin command
function __demo_rust_complete_plugin
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        echo 'list\tList all available and loaded plugins'
        echo 'ls\tList all available and loaded plugins'
        echo 'install\tInstall a plugin from crates.io'
        echo 'uninstall\tUninstall a plugin'
        echo 'remove\tUninstall a plugin'
        echo 'create\tCreate a new plugin template'
        echo 'info\tShow detailed information about a plugin'
    else
        switch $subcmd[1]
            case 'list' 'ls'
                echo '--json\tOutput as JSON'
                echo '--help\tShow help for plugin list'
                echo '-h\tShow help for plugin list'
            case 'install'
                echo '--global\tInstall globally'
                echo '-g\tInstall globally'
                echo '--version\tInstall specific version'
                echo '--help\tShow help for plugin install'
                echo '-h\tShow help for plugin install'
            case 'uninstall' 'remove'
                echo '--global\tUninstall globally'
                echo '-g\tUninstall globally'
                echo '--help\tShow help for plugin uninstall'
                echo '-h\tShow help for plugin uninstall'
            case 'create'
                echo '--type\tPlugin type (library|binary)'
                echo '--dir\tOutput directory'
                echo '--help\tShow help for plugin create'
                echo '-h\tShow help for plugin create'
            case 'info'
                echo '--help\tShow help for plugin info'
                echo '-h\tShow help for plugin info'
        end
    end
end

# Complete upgrade command
function __demo_rust_complete_upgrade
    echo '--check\tCheck for updates without installing'
    echo '--version\tInstall specific version'
    echo '--pre\tInclude pre-release versions'
    echo '--dry-run\tShow what would be done without doing it'
    echo '--help\tShow help for upgrade command'
    echo '-h\tShow help for upgrade command'
end

# Helper function to check if we're completing an option value
function __demo_rust_completing_option
    set -l cmd (commandline -opc)
    if test (count $cmd) -gt 1
        switch $cmd[-1]
            case '--version' '--type' '--dir'
                return 0
        end
    end
    return 1
end

# Register completions
complete -c demo_rust -f -a '(__demo_rust_complete)'

# Global options
complete -c demo_rust -l help -s h -d 'Show help information'
complete -c demo_rust -l version -s V -d 'Show version information'

# Command-specific completions with conditions
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -l style -d 'Greeting style'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -s s -d 'Greeting style'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -l count -d 'Repeat greeting N times'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -s c -d 'Repeat greeting N times'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -l uppercase -d 'Convert to uppercase'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -s u -d 'Convert to uppercase'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -l language -d 'Language code'
complete -c demo_rust -n '__fish_seen_subcommand_from greet' -s l -d 'Language code'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -l format -d 'Output format'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -s f -d 'Output format'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -l verbose -d 'Show detailed information'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -s v -d 'Show detailed information'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -l sections -d 'Comma-separated sections to show'
complete -c demo_rust -n '__fish_seen_subcommand_from info' -s s -d 'Comma-separated sections to show'

# Plugin command specific options
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from list' -l json -d 'Output as JSON'
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l global -s g -d 'Install globally'
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l version -d 'Install specific version'
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from uninstall' -l global -s g -d 'Uninstall globally'
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l type -d 'Plugin type' -a 'library binary'
complete -c demo_rust -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l dir -d 'Output directory' -a '(__fish_complete_directories)'

# Upgrade command options
complete -c demo_rust -n '__fish_seen_subcommand_from upgrade' -l check -d 'Check for updates without installing'
complete -c demo_rust -n '__fish_seen_subcommand_from upgrade' -l version -d 'Install specific version'
complete -c demo_rust -n '__fish_seen_subcommand_from upgrade' -l pre -d 'Include pre-release versions'
complete -c demo_rust -n '__fish_seen_subcommand_from upgrade' -l dry-run -d 'Show what would be done without doing it'

# File completion for certain options
complete -c demo_rust -n '__fish_prev_arg_in --config --file -f' -a '(__fish_complete_path)'
complete -c demo_rust -n '__fish_prev_arg_in --dir --directory -d' -a '(__fish_complete_directories)'