#!/bin/bash
# Setup script for test-multi-cli
# Generated by Goobits CLI Framework

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Project information
PACKAGE_NAME="test-multi-cli"
COMMAND_NAME="testmulti"
DISPLAY_NAME="test-multi-cli"

echo -e "${BLUE}Setting up ${DISPLAY_NAME}...${NC}"

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed${NC}"
    echo "Please install Node.js from https://nodejs.org/"
    exit 1
fi

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    echo "Please install npm (usually comes with Node.js)"
    exit 1
fi

echo -e "${GREEN}✓ Node.js and npm are installed${NC}"

# Install dependencies
echo -e "${BLUE}Installing dependencies...${NC}"
if npm install; then
    echo -e "${GREEN}✓ Dependencies installed successfully${NC}"
else
    echo -e "${RED}✗ Dependency installation failed${NC}"
    exit 1
fi

# Install globally
echo -e "${BLUE}Installing ${COMMAND_NAME} globally...${NC}"
if npm install -g .; then
    echo -e "${GREEN}✓ Installation completed successfully${NC}"
else
    echo -e "${RED}✗ Global installation failed${NC}"
    echo -e "${YELLOW}Trying to install with sudo...${NC}"
    if sudo npm install -g .; then
        echo -e "${GREEN}✓ Installation completed successfully${NC}"
    else
        echo -e "${RED}✗ Installation failed${NC}"
        exit 1
    fi
fi

# Verify installation
if command -v "$COMMAND_NAME" &> /dev/null; then
    echo -e "${GREEN}✓ ${COMMAND_NAME} is now available globally${NC}"
    echo -e "${BLUE}Version: $($COMMAND_NAME --version)${NC}"
else
    echo -e "${YELLOW}⚠ ${COMMAND_NAME} was installed but is not in your PATH${NC}"
fi

echo -e "${GREEN}Setup complete! You can now use '${COMMAND_NAME}' command.${NC}"
echo -e "${BLUE}Run '${COMMAND_NAME} --help' to get started.${NC}"