"""
Abstract base interface for language-specific renderers.

This module defines the LanguageRenderer interface that must be implemented
by each supported language (Python, Node.js, TypeScript, Rust).

This is a THIN interface per SRP - contains only the abstract contract,
no helper methods. Helpers are in helpers.py.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class Artifact:
    """
    Represents a generated file artifact.

    Attributes:
        path: Relative output path for the file
        content: Generated file content
        metadata: Optional metadata about the artifact
    """

    path: str
    content: str
    metadata: Optional[Dict[str, Any]] = None


class LanguageRenderer(ABC):
    """
    Abstract base class for language-specific renderers.

    Each supported language (Python, Node.js, TypeScript, Rust) must
    implement this interface to provide language-specific rendering logic.

    This interface follows the Single Responsibility Principle:
    - Only defines the contract for rendering
    - No implementation details or helper methods
    - Helpers are in renderers/helpers.py
    """

    @property
    @abstractmethod
    def language(self) -> str:
        """Return the language name (e.g., 'python', 'nodejs', 'typescript', 'rust')."""
        pass

    @property
    @abstractmethod
    def file_extensions(self) -> Dict[str, str]:
        """Return mapping of component types to file extensions for this language."""
        pass

    @abstractmethod
    def get_template_context(self, ir: Dict[str, Any]) -> Dict[str, Any]:
        """
        Transform the intermediate representation into language-specific template context.

        Args:
            ir: Intermediate representation generated by IRBuilder

        Returns:
            Language-specific template context for rendering
        """
        pass

    @abstractmethod
    def get_custom_filters(self) -> Dict[str, callable]:
        """
        Return custom Jinja2 filters specific to this language.

        Returns:
            Dictionary mapping filter names to filter functions
        """
        pass

    @abstractmethod
    def render_component(
        self, component_name: str, template_content: str, context: Dict[str, Any]
    ) -> str:
        """
        Render a specific component template for this language.

        Args:
            component_name: Name of the component being rendered
            template_content: The universal template content
            context: Language-specific template context

        Returns:
            Rendered template content for this language
        """
        pass

    @abstractmethod
    def get_output_structure(self, ir: Dict[str, Any]) -> Dict[str, str]:
        """
        Define the output file structure for this language.

        Args:
            ir: Intermediate representation

        Returns:
            Dictionary mapping component names to output file paths
        """
        pass

    def render(self, ir: Dict[str, Any]) -> List[Artifact]:
        """
        Render all artifacts for the given intermediate representation.

        This is the main entry point per the RENDERER_CONTRACT.md.

        Args:
            ir: Intermediate representation

        Returns:
            List of generated artifacts
        """
        context = self.get_template_context(ir)
        output_structure = self.get_output_structure(ir)
        artifacts = []

        for component_name, output_path in output_structure.items():
            # Subclasses implement render_component
            # Here we just define the contract
            content = self.render_component(component_name, "", context)
            artifacts.append(
                Artifact(
                    path=output_path,
                    content=content,
                    metadata={"component": component_name, "language": self.language},
                )
            )

        return artifacts


__all__ = ["LanguageRenderer", "Artifact"]
