"""
Abstract base class for language-specific renderers.

This module defines the LanguageRenderer interface that must be implemented
by each supported language (Python, Node.js, TypeScript, Rust).
"""

from abc import ABC, abstractmethod
from typing import Any, Dict


class LanguageRenderer(ABC):
    """
    Abstract base class for language-specific renderers.

    Each supported language (Python, Node.js, TypeScript, Rust) must
    implement this interface to provide language-specific rendering logic.

    This class defines the contract for:
    - Language identification
    - File extension mapping
    - Template context transformation
    - Custom Jinja2 filters
    - Component rendering
    - Output file structure
    """

    @property
    @abstractmethod
    def language(self) -> str:
        """Return the language name (e.g., 'python', 'nodejs', 'typescript', 'rust')"""

        pass

    @property
    @abstractmethod
    def file_extensions(self) -> Dict[str, str]:
        """Return mapping of component types to file extensions for this language"""

        pass

    @abstractmethod
    def get_template_context(self, ir: Dict[str, Any]) -> Dict[str, Any]:
        """

        Transform the intermediate representation into language-specific template context.

        Args:

            ir: Intermediate representation generated by UniversalTemplateEngine

        Returns:

            Language-specific template context for rendering

        """

        pass

    @abstractmethod
    def get_custom_filters(self) -> Dict[str, callable]:
        """

        Return custom Jinja2 filters specific to this language.

        Returns:

            Dictionary mapping filter names to filter functions

        """

        pass

    def _set_language_context(self, ir: Dict[str, Any]) -> Dict[str, Any]:
        """
        Helper method to set language context from IR, ensuring consistent language setting.

        Args:
            ir: Intermediate representation dictionary

        Returns:
            Context dictionary with language field set to this renderer's language
        """
        context = ir.copy()
        context["language"] = self.language
        return context

    @abstractmethod
    def render_component(
        self, component_name: str, template_content: str, context: Dict[str, Any]
    ) -> str:
        """

        Render a specific component template for this language.

        Args:

            component_name: Name of the component being rendered

            template_content: The universal template content

            context: Language-specific template context

        Returns:

            Rendered template content for this language

        """

        pass

    @abstractmethod
    def get_output_structure(self, ir: Dict[str, Any]) -> Dict[str, str]:
        """

        Define the output file structure for this language.

        Args:

            ir: Intermediate representation

        Returns:

            Dictionary mapping component names to output file paths

        """

        pass
