/**
 * Configuration types for Test TypeScript CLI CLI
 * Generated by Goobits CLI Framework
 */

export interface BaseConfig {
  debug?: boolean;
  verbose?: boolean;
  configPath?: string;
  [key: string]: any;
}

export interface GlobalConfig extends BaseConfig {}

export interface EnvironmentConfig {
  NODE_ENV?: string;
  DEBUG?: string;
  CONFIG_PATH?: string;
  HOME?: string;
  PWD?: string;
}

export interface ProjectConfig {
  name?: string;
  version?: string;
  description?: string;
  repository?: string;
  homepage?: string;
  bugsUrl?: string;
  keywords?: string[];
  author?: string;
  license?: string;
}

export interface CLIConfig extends BaseConfig {
  project?: ProjectConfig;
  environment?: EnvironmentConfig;  commands?: {    hello?: HelloConfig;    build?: BuildConfig;    serve?: ServeConfig;  };}
export interface HelloConfig {  [key: string]: any;
}
export interface BuildConfig {  [key: string]: any;
}
export interface ServeConfig {  [key: string]: any;
}
export interface ConfigManager {
  load(path?: string): Promise<CLIConfig>;
  save(config: CLIConfig, path?: string): Promise<void>;
  validate(config: any): CLIConfig;
  merge(...configs: Partial<CLIConfig>[]): CLIConfig;
  getDefaults(): CLIConfig;
}