/**
 * Error types for Test TypeScript CLI CLI
 * Generated by Goobits CLI Framework
 */

export interface CLIError {
  message: string;
  code?: string | number;
  details?: Record<string, any>;
}

export interface ValidationError extends CLIError {
  field?: string;
  value?: any;
  constraints?: string[];
}

export interface CommandError extends CLIError {
  command?: string;
  exitCode?: number;
}

export interface ConfigError extends CLIError {
  configPath?: string;
  section?: string;
}

export interface NetworkError extends CLIError {
  url?: string;
  statusCode?: number;
  timeout?: boolean;
}

export class CLIException extends Error implements CLIError {
  public code?: string | number;
  public details?: Record<string, any>;

  constructor(message: string, code?: string | number, details?: Record<string, any>) {
    super(message);
    this.name = 'CLIException';
    this.code = code;
    this.details = details;
  }
}

export class ValidationException extends CLIException implements ValidationError {
  public field?: string;
  public value?: any;
  public constraints?: string[];

  constructor(
    message: string, 
    field?: string, 
    value?: any, 
    constraints?: string[],
    code?: string | number
  ) {
    super(message, code);
    this.name = 'ValidationException';
    this.field = field;
    this.value = value;
    this.constraints = constraints;
  }
}

export class CommandException extends CLIException implements CommandError {
  public command?: string;
  public exitCode?: number;

  constructor(message: string, command?: string, exitCode?: number, code?: string | number) {
    super(message, code);
    this.name = 'CommandException';
    this.command = command;
    this.exitCode = exitCode;
  }
}