# Fish completion script for NodeJSTestCLI (nodejstestcli)
# Auto-generated by goobits-cli

# Main completion function
function __nodejstestcli_complete
    set -l cmd (commandline -opc)
    set -l current (commandline -ct)
    
    # Try dynamic completion first
    if __nodejstestcli_dynamic_complete $cmd $current
        return 0
    end
    
    # Fallback to static completion
    __nodejstestcli_static_complete $cmd $current
end

# Dynamic completion using CLI's built-in completion
function __nodejstestcli_dynamic_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Check if CLI supports completion
    if not command -v nodejstestcli >/dev/null 2>&1
        return 1
    end
    
    # Get completion suggestions from the CLI itself
    set -l suggestions (nodejstestcli _completion fish (commandline -cp) (commandline -C) 2>/dev/null)
    
    if test $status -eq 0; and test -n "$suggestions"
        for suggestion in $suggestions
            echo $suggestion
        end
        return 0
    end
    
    return 1
end

# Static completion as fallback
function __nodejstestcli_static_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Remove the command name itself
    set -e cmd[1]
    
    # If no subcommand yet, complete with main commands
    if test (count $cmd) -eq 0
        __nodejstestcli_complete_commands
        return 0
    end
    
    # Handle subcommand completion
    switch $cmd[1]
        case 'init'
            __nodejstestcli_complete_init_options $cmd[2..-1]
        case 'deploy'
            __nodejstestcli_complete_deploy_options $cmd[2..-1]
        case 'server'
            __nodejstestcli_complete_server_subcommands $cmd[2..-1]
        case 'database'
            __nodejstestcli_complete_database_subcommands $cmd[2..-1]
        case 'test'
            __nodejstestcli_complete_test_options $cmd[2..-1]
        case 'plugin'
            __nodejstestcli_complete_plugin $cmd[2..-1]
        case 'upgrade'
            __nodejstestcli_complete_upgrade $cmd[2..-1]
        case 'help'
            __nodejstestcli_complete_commands
    end
end

# Complete main commands
function __nodejstestcli_complete_commands
    echo 'init\tInitialize a new project'
    echo 'deploy\tDeploy the application'
    echo 'server\tServer management commands'
    echo 'database\tDatabase operations'
    echo 'test\tRun tests'
    echo 'upgrade\tUpgrade NodeJSTestCLI to the latest version'
    echo 'plugin\t🔌 Manage plugins for NodeJSTestCLI'
    echo 'help\tShow help information'
end

# Complete init command options
function __nodejstestcli_complete_init_options
    echo '--template\tProject template to use'
    echo '-t\tProject template to use'
    echo '--skip-install\tSkip npm install'
    echo '--help\tShow help for init command'
    echo '-h\tShow help for init command'
end
# Complete deploy command options
function __nodejstestcli_complete_deploy_options
    echo '--force\tForce deployment without confirmation'
    echo '-f\tForce deployment without confirmation'
    echo '--dry-run\tSimulate deployment without making changes'
    echo '--help\tShow help for deploy command'
    echo '-h\tShow help for deploy command'
end
# Complete server subcommands
function __nodejstestcli_complete_server_subcommands
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        # List subcommands
        echo 'start\tStart the server'
        echo 'stop\tStop the server'
        echo 'restart\tRestart the server'
    else
        # Complete subcommand options
        switch $subcmd[1]
            case 'start'
                echo '--port\tPort to listen on'
                echo '-p\tPort to listen on'
                echo '--daemon\tRun as daemon'
                echo '-d\tRun as daemon'
                echo '--help\tShow help for start subcommand'
                echo '-h\tShow help for start subcommand'
            case 'stop'
                echo '--graceful\tGraceful shutdown'
                echo '--help\tShow help for stop subcommand'
                echo '-h\tShow help for stop subcommand'
            case 'restart'
                echo '--help\tShow help for restart subcommand'
                echo '-h\tShow help for restart subcommand'
        end
    end
end
# Complete database subcommands
function __nodejstestcli_complete_database_subcommands
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        # List subcommands
        echo 'migrate\tRun database migrations'
        echo 'seed\tSeed the database'
        echo 'backup\tBackup the database'
    else
        # Complete subcommand options
        switch $subcmd[1]
            case 'migrate'
                echo '--direction\tMigration direction (up/down)'
                echo '--steps\tNumber of migrations to run'
                echo '--help\tShow help for migrate subcommand'
                echo '-h\tShow help for migrate subcommand'
            case 'seed'
                echo '--truncate\tTruncate tables before seeding'
                echo '--help\tShow help for seed subcommand'
                echo '-h\tShow help for seed subcommand'
            case 'backup'
                echo '--output\tOutput file path'
                echo '-o\tOutput file path'
                echo '--compress\tCompress the backup'
                echo '--help\tShow help for backup subcommand'
                echo '-h\tShow help for backup subcommand'
        end
    end
end
# Complete test command options
function __nodejstestcli_complete_test_options
    echo '--coverage\tGenerate coverage report'
    echo '--watch\tWatch files for changes'
    echo '-w\tWatch files for changes'
    echo '--bail\tStop on first test failure'
    echo '--help\tShow help for test command'
    echo '-h\tShow help for test command'
end

# Complete plugin command
function __nodejstestcli_complete_plugin
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        echo 'list\tList all available and loaded plugins'
        echo 'ls\tList all available and loaded plugins'
        echo 'install\tInstall a plugin from npm'
        echo 'uninstall\tUninstall a plugin'
        echo 'remove\tUninstall a plugin'
        echo 'create\tCreate a new plugin template'
        echo 'info\tShow detailed information about a plugin'
    else
        switch $subcmd[1]
            case 'list' 'ls'
                echo '--json\tOutput as JSON'
                echo '--help\tShow help for plugin list'
                echo '-h\tShow help for plugin list'
            case 'install'
                echo '--global\tInstall globally'
                echo '-g\tInstall globally'
                echo '--version\tInstall specific version'
                echo '--help\tShow help for plugin install'
                echo '-h\tShow help for plugin install'
            case 'uninstall' 'remove'
                echo '--global\tUninstall globally'
                echo '-g\tUninstall globally'
                echo '--help\tShow help for plugin uninstall'
                echo '-h\tShow help for plugin uninstall'
            case 'create'
                echo '--type\tPlugin type (function|class|npm)'
                echo '--dir\tOutput directory'
                echo '--help\tShow help for plugin create'
                echo '-h\tShow help for plugin create'
            case 'info'
                echo '--help\tShow help for plugin info'
                echo '-h\tShow help for plugin info'
        end
    end
end

# Complete upgrade command
function __nodejstestcli_complete_upgrade
    echo '--check\tCheck for updates without installing'
    echo '--version\tInstall specific version'
    echo '--pre\tInclude pre-release versions'
    echo '--dry-run\tShow what would be done without doing it'
    echo '--help\tShow help for upgrade command'
    echo '-h\tShow help for upgrade command'
end

# Helper function to check if we're completing an option value
function __nodejstestcli_completing_option
    set -l cmd (commandline -opc)
    if test (count $cmd) -gt 1
        switch $cmd[-1]
            case '--version' '--type' '--dir'
                return 0
        end
    end
    return 1
end

# Register completions
complete -c nodejstestcli -f -a '(__nodejstestcli_complete)'

# Global options
complete -c nodejstestcli -l verbose -d 'Enable verbose logging'
complete -c nodejstestcli -s v -d 'Enable verbose logging'
complete -c nodejstestcli -l config -d 'Path to configuration file'
complete -c nodejstestcli -s c -d 'Path to configuration file'
complete -c nodejstestcli -l help -s h -d 'Show help information'
complete -c nodejstestcli -l version -s V -d 'Show version information'

# Command-specific completions with conditions
complete -c nodejstestcli -n '__fish_seen_subcommand_from init' -l template -d 'Project template to use'
complete -c nodejstestcli -n '__fish_seen_subcommand_from init' -s t -d 'Project template to use'
complete -c nodejstestcli -n '__fish_seen_subcommand_from init' -l skip-install -d 'Skip npm install'
complete -c nodejstestcli -n '__fish_seen_subcommand_from deploy' -l force -d 'Force deployment without confirmation'
complete -c nodejstestcli -n '__fish_seen_subcommand_from deploy' -s f -d 'Force deployment without confirmation'
complete -c nodejstestcli -n '__fish_seen_subcommand_from deploy' -l dry-run -d 'Simulate deployment without making changes'
complete -c nodejstestcli -n '__fish_seen_subcommand_from test' -l coverage -d 'Generate coverage report'
complete -c nodejstestcli -n '__fish_seen_subcommand_from test' -l watch -d 'Watch files for changes'
complete -c nodejstestcli -n '__fish_seen_subcommand_from test' -s w -d 'Watch files for changes'
complete -c nodejstestcli -n '__fish_seen_subcommand_from test' -l bail -d 'Stop on first test failure'

# Plugin command specific options
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from list' -l json -d 'Output as JSON'
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l global -s g -d 'Install globally'
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l version -d 'Install specific version'
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from uninstall' -l global -s g -d 'Uninstall globally'
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l type -d 'Plugin type' -a 'function class npm'
complete -c nodejstestcli -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l dir -d 'Output directory' -a '(__fish_complete_directories)'

# Upgrade command options
complete -c nodejstestcli -n '__fish_seen_subcommand_from upgrade' -l check -d 'Check for updates without installing'
complete -c nodejstestcli -n '__fish_seen_subcommand_from upgrade' -l version -d 'Install specific version'
complete -c nodejstestcli -n '__fish_seen_subcommand_from upgrade' -l pre -d 'Include pre-release versions'
complete -c nodejstestcli -n '__fish_seen_subcommand_from upgrade' -l dry-run -d 'Show what would be done without doing it'

# File completion for certain options
complete -c nodejstestcli -n '__fish_prev_arg_in --config --file -f' -a '(__fish_complete_path)'
complete -c nodejstestcli -n '__fish_prev_arg_in --dir --directory -d' -a '(__fish_complete_directories)'