# Fish completion script for Test 3-Level Commands (test3level)
# Auto-generated by goobits-cli

# Main completion function
function __test3level_complete
    set -l cmd (commandline -opc)
    set -l current (commandline -ct)
    
    # Try dynamic completion first
    if __test3level_dynamic_complete $cmd $current
        return 0
    end
    
    # Fallback to static completion
    __test3level_static_complete $cmd $current
end

# Dynamic completion using CLI's built-in completion
function __test3level_dynamic_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Check if CLI supports completion
    if not command -v test3level >/dev/null 2>&1
        return 1
    end
    
    # Get completion suggestions from the CLI itself
    set -l suggestions (test3level _completion fish (commandline -cp) (commandline -C) 2>/dev/null)
    
    if test $status -eq 0; and test -n "$suggestions"
        for suggestion in $suggestions
            echo $suggestion
        end
        return 0
    end
    
    return 1
end

# Static completion as fallback
function __test3level_static_complete
    set -l cmd $argv[1..-2]
    set -l current $argv[-1]
    
    # Remove the command name itself
    set -e cmd[1]
    
    # If no subcommand yet, complete with main commands
    if test (count $cmd) -eq 0
        __test3level_complete_commands
        return 0
    end
    
    # Handle subcommand completion
    switch $cmd[1]
        case 'simple'
            __test3level_complete_simple_options $cmd[2..-1]
        case 'api'
            __test3level_complete_api_subcommands $cmd[2..-1]
        case 'nested'
            __test3level_complete_nested_subcommands $cmd[2..-1]
        case 'plugin'
            __test3level_complete_plugin $cmd[2..-1]
        case 'upgrade'
            __test3level_complete_upgrade $cmd[2..-1]
        case 'help'
            __test3level_complete_commands
    end
end

# Complete main commands
function __test3level_complete_commands
    echo 'simple\tSimple command'
    echo 'api\tAPI management'
    echo 'nested\tNested command test'
    echo 'upgrade\tUpgrade Test 3-Level Commands to the latest version'
    echo 'plugin\t🔌 Manage plugins for Test 3-Level Commands'
    echo 'help\tShow help information'
end

# Complete simple command options
function __test3level_complete_simple_options
    echo '--help\tShow help for simple command'
    echo '-h\tShow help for simple command'
end
# Complete api subcommands
function __test3level_complete_api_subcommands
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        # List subcommands
        echo 'v1\tAPI v1 endpoints'
    else
        # Complete subcommand options
        switch $subcmd[1]
            case 'v1'
                echo '--help\tShow help for v1 subcommand'
                echo '-h\tShow help for v1 subcommand'
        end
    end
end
# Complete nested subcommands
function __test3level_complete_nested_subcommands
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        # List subcommands
        echo 'level2\tLevel 2 subcommand'
    else
        # Complete subcommand options
        switch $subcmd[1]
            case 'level2'
                echo '--help\tShow help for level2 subcommand'
                echo '-h\tShow help for level2 subcommand'
        end
    end
end

# Complete plugin command
function __test3level_complete_plugin
    set -l subcmd $argv
    
    if test (count $subcmd) -eq 0
        echo 'list\tList all available and loaded plugins'
        echo 'ls\tList all available and loaded plugins'
        echo 'install\tInstall a plugin from npm'
        echo 'uninstall\tUninstall a plugin'
        echo 'remove\tUninstall a plugin'
        echo 'create\tCreate a new plugin template'
        echo 'info\tShow detailed information about a plugin'
    else
        switch $subcmd[1]
            case 'list' 'ls'
                echo '--json\tOutput as JSON'
                echo '--help\tShow help for plugin list'
                echo '-h\tShow help for plugin list'
            case 'install'
                echo '--global\tInstall globally'
                echo '-g\tInstall globally'
                echo '--version\tInstall specific version'
                echo '--help\tShow help for plugin install'
                echo '-h\tShow help for plugin install'
            case 'uninstall' 'remove'
                echo '--global\tUninstall globally'
                echo '-g\tUninstall globally'
                echo '--help\tShow help for plugin uninstall'
                echo '-h\tShow help for plugin uninstall'
            case 'create'
                echo '--type\tPlugin type (function|class|npm)'
                echo '--dir\tOutput directory'
                echo '--help\tShow help for plugin create'
                echo '-h\tShow help for plugin create'
            case 'info'
                echo '--help\tShow help for plugin info'
                echo '-h\tShow help for plugin info'
        end
    end
end

# Complete upgrade command
function __test3level_complete_upgrade
    echo '--check\tCheck for updates without installing'
    echo '--version\tInstall specific version'
    echo '--pre\tInclude pre-release versions'
    echo '--dry-run\tShow what would be done without doing it'
    echo '--help\tShow help for upgrade command'
    echo '-h\tShow help for upgrade command'
end

# Helper function to check if we're completing an option value
function __test3level_completing_option
    set -l cmd (commandline -opc)
    if test (count $cmd) -gt 1
        switch $cmd[-1]
            case '--version' '--type' '--dir'
                return 0
        end
    end
    return 1
end

# Register completions
complete -c test3level -f -a '(__test3level_complete)'

# Global options
complete -c test3level -l help -s h -d 'Show help information'
complete -c test3level -l version -s V -d 'Show version information'

# Command-specific completions with conditions

# Plugin command specific options
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from list' -l json -d 'Output as JSON'
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l global -s g -d 'Install globally'
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from install' -l version -d 'Install specific version'
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from uninstall' -l global -s g -d 'Uninstall globally'
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l type -d 'Plugin type' -a 'function class npm'
complete -c test3level -n '__fish_seen_subcommand_from plugin; and __fish_seen_subcommand_from create' -l dir -d 'Output directory' -a '(__fish_complete_directories)'

# Upgrade command options
complete -c test3level -n '__fish_seen_subcommand_from upgrade' -l check -d 'Check for updates without installing'
complete -c test3level -n '__fish_seen_subcommand_from upgrade' -l version -d 'Install specific version'
complete -c test3level -n '__fish_seen_subcommand_from upgrade' -l pre -d 'Include pre-release versions'
complete -c test3level -n '__fish_seen_subcommand_from upgrade' -l dry-run -d 'Show what would be done without doing it'

# File completion for certain options
complete -c test3level -n '__fish_prev_arg_in --config --file -f' -a '(__fish_complete_path)'
complete -c test3level -n '__fish_prev_arg_in --dir --directory -d' -a '(__fish_complete_directories)'