#!/bin/bash
# Bash completion script for TestConflictCLI (testconflict)
# Auto-generated by goobits-cli

_testconflict_completions() {
    local cur prev words cword
    _init_completion || return

    # Get the current CLI binary path
    local cli_bin="testconflict"
    
    # Check if CLI supports completion
    if ! command -v "$cli_bin" >/dev/null 2>&1; then
        return 0
    fi
    
    # Get completion suggestions from the CLI itself
    local suggestions
    suggestions=$("$cli_bin" _completion bash "$COMP_LINE" "$COMP_POINT" 2>/dev/null)
    
    if [[ $? -eq 0 && -n "$suggestions" ]]; then
        COMPREPLY=($(compgen -W "$suggestions" -- "$cur"))
        return 0
    fi
    
    # Fallback to static completions
    case "${prev}" in
        testconflict)
            # Top level commands
            local commands="config completion daemon plugin upgrade plugin help"
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
            return 0
            ;;
        config)
            # Options for config
            local options="--key --value --help -h"
            COMPREPLY=($(compgen -W "$options" -- "$cur"))
            return 0
            ;;
        completion)
            # Options for completion
            local options="--shell --help -h"
            COMPREPLY=($(compgen -W "$options" -- "$cur"))
            return 0
            ;;
        daemon)
            # Options for daemon
            local options="--action --help -h"
            COMPREPLY=($(compgen -W "$options" -- "$cur"))
            return 0
            ;;
        plugin)
            # Options for plugin
            local options="--name --help -h"
            COMPREPLY=($(compgen -W "$options" -- "$cur"))
            return 0
            ;;
        plugin)
            local plugin_commands="list install uninstall create info help"
            COMPREPLY=($(compgen -W "$plugin_commands" -- "$cur"))
            return 0
            ;;
        upgrade)
            local upgrade_options="--check --version --pre --dry-run --help -h"
            COMPREPLY=($(compgen -W "$upgrade_options" -- "$cur"))
            return 0
            ;;
        --version|-V)
            # Don't complete after version flags
            return 0
            ;;
        --help|-h)
            # Don't complete after help flags
            return 0
            ;;
        *)
            # Global options
            local global_options="--help -h --version -V"
            
            # Check if we're in a subcommand context
            local i=1
            local in_subcommand=""
            while [[ $i -lt $cword ]]; do
                case "${words[$i]}" in
                    config)
                        in_subcommand="config"
                        break
                        ;;
                    completion)
                        in_subcommand="completion"
                        break
                        ;;
                    daemon)
                        in_subcommand="daemon"
                        break
                        ;;
                    plugin)
                        in_subcommand="plugin"
                        break
                        ;;
                    plugin|upgrade)
                        in_subcommand="${words[$i]}"
                        break
                        ;;
                esac
                ((i++))
            done
            
            if [[ -n "$in_subcommand" ]]; then
                # We're in a subcommand, offer subcommand-specific options
                case "$in_subcommand" in
                    config)
                        local cmd_options="--key --value --help -h"
                        COMPREPLY=($(compgen -W "$cmd_options" -- "$cur"))
                        ;;
                    completion)
                        local cmd_options="--shell --help -h"
                        COMPREPLY=($(compgen -W "$cmd_options" -- "$cur"))
                        ;;
                    daemon)
                        local cmd_options="--action --help -h"
                        COMPREPLY=($(compgen -W "$cmd_options" -- "$cur"))
                        ;;
                    plugin)
                        local cmd_options="--name --help -h"
                        COMPREPLY=($(compgen -W "$cmd_options" -- "$cur"))
                        ;;
                    plugin)
                        local plugin_options="--json --global --version --type --dir --help -h"
                        COMPREPLY=($(compgen -W "$plugin_options" -- "$cur"))
                        ;;
                    upgrade)
                        local upgrade_options="--check --version --pre --dry-run --help -h"
                        COMPREPLY=($(compgen -W "$upgrade_options" -- "$cur"))
                        ;;
                esac
            else
                COMPREPLY=($(compgen -W "$global_options" -- "$cur"))
            fi
            return 0
            ;;
    esac

    # File completion for certain options
    case "${prev}" in
        --config|--file|-f)
            COMPREPLY=($(compgen -f -- "$cur"))
            return 0
            ;;
        --dir|--directory|-d)
            COMPREPLY=($(compgen -d -- "$cur"))
            return 0
            ;;
    esac

    return 0
}

# Register the completion function
complete -F _testconflict_completions testconflict

# Also register for common variations

# Support for npm global installation
if [[ -n "${NPM_CONFIG_PREFIX:-}" ]]; then
    complete -F _testconflict_completions "${NPM_CONFIG_PREFIX}/bin/testconflict"
fi