/**
 * ╔════════════════════════════════════════════════════════════════════════════╗
 * ║                        AUTO-GENERATED FILE                               ║
 * ║  Generated by: goobits-cli v1.0.0                     ║
 * ║  ⚠️  DO NOT EDIT - Changes will be overwritten                           ║
 * ╚════════════════════════════════════════════════════════════════════════════╝
 * 
 * Main CLI implementation for Test TypeScript
 * Generated from: goobits.yaml
 */

import { Command } from 'commander';
import chalk from 'chalk';
import * as hooks from './src/hooks.js';

// Simple types for the CLI
interface CommandArgs {
  commandName: string;
  rawArgs?: Record<string, any>;
  [key: string]: any;
}

// Create the main program
const program = new Command();

// Main CLI setup
export function cli(): void {
  program
    .name('testts')
    .description('Test TypeScript helper libraries')
    .version('1.0.0');

  // Define commands from configuration
  program
    .command('hello')
    .description('Say hello')
    .argument('<name>', 'Name to greet')
    .action(async (name, options: any) => {
      const args: CommandArgs = {
        commandName: 'hello',
        rawArgs: options,
        name,
      };
      
      try {
        const hookName = 'onHello';
        if (hooks && typeof hooks[hookName as keyof typeof hooks] === 'function') {
          await (hooks[hookName as keyof typeof hooks] as (args: CommandArgs) => Promise<void>)(args);
        } else {
          console.log(chalk.blue(`Executing hello command...`));
          console.log(`  name:`, name);
          console.log('Options:', options);
        }
      } catch (error) {
        console.error(chalk.red(`Error executing hello:`), error);
        process.exit(1);
      }
    });

  // Parse arguments
  program.parse(process.argv);
  
  // Show help if no arguments provided
  if (!process.argv.slice(2).length) {
    program.outputHelp();
  }
}

// Export for use as a module
export default cli;