/**
 * A sample Node.js CLI built with Goobits
 * Generated by Goobits CLI Framework using Universal Templates
 * 
 * Entry point: demo_js
 */

import { Command } from 'commander';
import * as hooks from './src/hooks.js';

const program = new Command();

program
  .name('demo_js')
  .description('Node.js CLI demonstration')
  .version('1.0.0');
// greet command
program
  .command('greet')
  .description('')  .option('-s, --style <value>', '')  .option('-c, --count <value>', '')  .option('-u, --uppercase', '')  .option('-l, --language <value>', '')  .action(async (options) => {
    const args = {
      commandName: 'greet',
      rawArgs: options,    };
    
    try {
      const hookFunction = hooks.onGreet;
      if (hookFunction) {
        await hookFunction(args);
      } else {
        console.log(`No hook implementation found for command: ${args.commandName}`);
      }
    } catch (error) {
      console.error(`Error executing greet:`, error.message);
      process.exit(1);
    }
  });
// info command
program
  .command('info')
  .description('')  .option('-f, --format <value>', '')  .option('-v, --verbose', '')  .option('-s, --sections <value>', '')  .action(async (options) => {
    const args = {
      commandName: 'info',
      rawArgs: options,    };
    
    try {
      const hookFunction = hooks.onInfo;
      if (hookFunction) {
        await hookFunction(args);
      } else {
        console.log(`No hook implementation found for command: ${args.commandName}`);
      }
    } catch (error) {
      console.error(`Error executing info:`, error.message);
      process.exit(1);
    }
  });
// Main CLI function
export function cli() {
  program.parse(process.argv);
  
  // Show help if no command provided
  if (!process.argv.slice(2).length) {
    program.outputHelp();
  }
}

// Export for use as a module
export default cli;

// Auto-run if this is the main module
if (import.meta.url === `file://${process.argv[1]}`) {
  cli();
}